# Generated by Django 5.0.6 on 2024-06-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MangoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inversor',
            old_name='company',
            new_name='nombre_empresa',
        ),
        migrations.RenameField(
            model_name='inversor',
            old_name='rubro',
            new_name='rubro_empresa',
        ),
        migrations.AddField(
            model_name='inversor',
            name='capital_inicial',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
