# Generated by Django 5.0.6 on 2024-06-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MangoApp', '0002_rename_company_inversor_nombre_empresa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprendedor',
            name='money_need',
        ),
        migrations.AddField(
            model_name='emprendedor',
            name='dinero_requerido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='emprendedor',
            name='emprendimiento',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emprendedor',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
