# Generated by Django 5.0.6 on 2024-06-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MangoApp', '0003_remove_emprendedor_money_need_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprador',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
